library(rvest)
library(dplyr)
link <- 'http://www.howstat.com/cricket/statistics/batting/Batting50Plus_T20.asp?S=1'
#path = path_allowed(link)
web <- read_html(link)
name <- web %>% html_nodes(".LinkTable")%>% html_text()
View(name)
runs <- web %>% html_nodes("tr+ tr td:nth-child(7)")%>% html_text()
View(runs)
average <- web %>%html_nodes("tr+ tr td:nth-child(12)")%>% html_text()
View(average)
matches <- web %>%html_nodes("tr+ tr td:nth-child(4)")%>% html_text()
View(matches)
batting_records<- data.frame(name,runs,average,matches)
View(batting_records)
write.csv (imdb.ratings,"my_T20_batting_records.csv")
